/// Flutter icons FluentSystemIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FluentSystemIcons
///      fonts:
///       - asset: fonts/FluentSystemIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FluentSystemIcons {
  FluentSystemIcons._();

  static const _kFontFam = 'FluentSystemIcons';
  static const _kFontPkg = null;

  static const IconData ic_fluent_calendar_24_filled = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_fluent_calendar_24_regular = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_fluent_certificate_24_filled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_fluent_certificate_24_regular = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_fluent_chat_24_filled = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_fluent_chat_24_regular = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_fluent_city_24_filled = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_fluent_city_24_regular = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
